name: CI Secret Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print secret (for test)
        run: |
          echo "Secret length:"
          echo ${#MY_SECRET}
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
